---
title: "FHS_RMST.Rmd"
author: "Grace Rade"
date: "7/5/2022"
output: pdf_document
---
```{r}
library(survival)
library(tidyverse)
library(rio)
library(survminer)
library(haven)
library(survRM2)


all_data <- read_sas('alldata2022.sas7bdat copy')
cvd_status <- read_dta("FHS 2154 - datasets/dr281_vr_survcvd_2014_a_1023s.dta") %>% select(IDTYPE, ranid, cvd, chd, chf)
last_contact <- read_dta("FHS 2154 - datasets/dr281_vr_survdth_2014_a_1025s.dta")
event_data <- read_dta("FHS 2154 - datasets/dr281_vr_soe_2016_a_1073s.dta") %>% 
  select(IDTYPE, ranid, EVENT, DATE)
all_data2 <- all_data %>% 
  inner_join(last_contact, by = c("IDTYPE", "ranid")) 
all_data2 <- all_data2 %>% 
  inner_join(event_data, by = c("IDTYPE", "ranid"))


all_data2$LASTCON[is.na(all_data2$LASTCON)] <- all_data2$DATEDTH[is.na(all_data2$LASTCON)] ## replacing values of last contact with date of death when applicable

all_data2 <- all_data2 %>% 
  mutate(dead = if_else(LASTCON > 5000, 1, 0)) ## alive = 1, dead = 0
  

all_data2$LASTCON[all_data2$LASTCON > 5000] <- 5000

all_data2 <- all_data2 %>% 
  mutate(censor = if_else(LASTCON >= 5000, 1, 0)) %>% 
  mutate(days = if_else(censor == 0, DATEDTH - examdate3_8, LASTCON - examdate3_8))


quantile(all_data2$TXB2_M) ## finding the quantiles for thromboxane levels

data_rmst <- all_data2 %>% 
  select(IDTYPE, ranid, TXB2_M, TXB2_M_I, H010, chfyn, chfdays, chfdate, afibyn, afibdate, afibdays, miyn, midate, CVDDEATH, CHDDEATH, DATEDTH, LASTCON, dead, DATE, days, censor) %>% 
  mutate(TXB2_quart = if_else(TXB2_M >= 4303.825, "Q4", NULL))

data_rmst$TXB2_quart[data_rmst$TXB2_M < 4303.825] <- "Q3"
data_rmst$TXB2_quart[data_rmst$TXB2_M < 1997.950] <- "Q2"
data_rmst$TXB2_quart[data_rmst$TXB2_M < 919.375] <- "Q1"

data_rmst <- data_rmst %>% 
  mutate(TXB2_quant = if_else(TXB2_M >= 4303.825, "Q4", "Q1-Q3"), events = if_else(CHDDEATH == 0, 1, 0)) %>% 
  rename(aspirin_use = H010)

data_rmst$events[data_rmst$CVDDEATH == 0] <- 2
data_rmst$events[data_rmst$chfyn == 0] <- 3
data_rmst$events[data_rmst$LASTCON == 5000] <- 0


all_data3 <- all_data %>% 
  inner_join(last_contact, by = c("IDTYPE", "ranid")) %>% 
  mutate(TXB2_quart = if_else(TXB2_M >= 4303.825, "Q4", NULL))

## txb2 quartiles
all_data3$TXB2_quart[all_data3$TXB2_M < 4303.825] <- "Q3"
all_data3$TXB2_quart[all_data3$TXB2_M < 1997.950] <- "Q2"
all_data3$TXB2_quart[all_data3$TXB2_M < 919.375] <- "Q1"

all_data3 <- all_data3 %>% 
  mutate(TXB2_quant = if_else(TXB2_M >= 4303.825, "Q4", "Q1-Q3"), events = if_else(CHDDEATH == 0, 1, 0)) %>% 
  mutate(days = if_else(is.na(DATEDTH), LASTCON - examdate3_8, DATEDTH- examdate3_8)) %>% 
  mutate(censor = if_else(is.na(DATEDTH), 1, 0))

## calculate the days lived after first exam (like SAS program), censor variable 


## all_data4 corrects the TXB2 quartiles by aspirin groups
all_data4 <- all_data %>% 
  inner_join(last_contact, by = c("IDTYPE", "ranid")) %>% 
  mutate(days = if_else(is.na(DATEDTH), LASTCON - examdate3_8, DATEDTH- examdate3_8)) 

## find the quartiles for each aspirin group
group_by(all_data4, H010) %>% 
  summarize(quart25 = quantile(TXB2_M, probs = 0.25), quart50 = quantile(TXB2_M, probs = 0.5), quart75 = quantile(TXB2_M, probs = 0.75))
 
## TXB2_M quartiles for aspirin = 0 group (no use) 
all_data4_aspirin0 <- all_data4 %>% 
  filter(H010 == 0) %>% 
  mutate(TXB2_quart = if_else(TXB2_M >= 5823, "Q4", NULL))

all_data4_aspirin0$TXB2_quart[all_data4_aspirin0$TXB2_M < 5823] <- "Q3"
all_data4_aspirin0$TXB2_quart[all_data4_aspirin0$TXB2_M < 3639] <- "Q2"
all_data4_aspirin0$TXB2_quart[all_data4_aspirin0$TXB2_M < 1698] <- "Q1"


## TXB2_M quartiles for aspirin = 1 group (use)
all_data4_aspirin1 <- all_data4 %>% 
  filter(H010 == 1) %>% 
  mutate(TXB2_quart = if_else(TXB2_M >= 1952, "Q4", NULL))

all_data4_aspirin1$TXB2_quart[all_data4_aspirin1$TXB2_M < 1952] <- "Q3"
all_data4_aspirin1$TXB2_quart[all_data4_aspirin1$TXB2_M < 1135] <- "Q2"
all_data4_aspirin1$TXB2_quart[all_data4_aspirin1$TXB2_M < 622] <- "Q1"


## rejoin the grouped datasets together by all variables
all_data4 <- all_data4_aspirin0 %>% 
  full_join(all_data4_aspirin1) 

## censor and days variables
all_data4 <- all_data4 %>% 
  mutate(days = if_else(is.na(DATEDTH), LASTCON - examdate3_8, DATEDTH- examdate3_8)) %>% 
  mutate(censor = if_else(is.na(DATEDTH), 1, 0))

export(data_rmst, "rmst_data.csv")
export(all_data2, "all_data.csv")
export(all_data3, "data_all.csv")
export(all_data4, "data4.csv")
## creating a new dataset with thromboxane quartile variables (one with categories of all 4 quartiles, one with categories 'q4' or 'q1-q3'), and a event categorical variable (assumed that in the cvdyn/chdyn variables that occurrence is categorized as 1) 

## as far as i can tell, there is no cancer variable
```

H010:

0 = no aspirin use

1 = aspirin use
## RMST
```{r}
model1 <- survfit(Surv(chfdays) ~ H010, data = all_data2)

ggsurvplot(model1, data = all_data2)

# trying to get R to calculate RMST is not something I've been successful at, disregard this curve

# the bump at the beginning of both curves confuses me
```


