---
title: "FHS_RBC_EDA"
author: "Grace Rade"
date: "2022-10-13"
output: html_document
---
```{r}
library(survival)
library(tidyverse)
library(rio)
library(survminer)
library(haven)
library(survRM2)


## load the datasets
all_data <- read_csv('rmst_methods_paper7.csv')
rbc_data <- read_dta("datasets_copy/dr281_l_rbcfa_2008_m_0420s_v1.dta")
last_contact <- read_sas("datasets_copy/dr281_vr_survdth_2019_a_1337s.sas7bdat")
cvd_data <- read_dta("FHS 2154 - datasets/dr281_vr_survcvd_2014_a_1023s.dta") %>% 
  select(IDTYPE, ranid, cvd, chd, chf)
event_data <- read_sas("datasets_copy/dr281_vr_soe_2020_a_1340s.sas7bdat") %>%
  select(idtype, ranid, DATE, EVENT) %>% 
  rename(IDTYPE = idtype) %>% 
  filter(EVENT %in% c(20, 21, 22, 23, 24, 25, 26, 27, 28, 29))

all_data2 <- all_data %>% 
  left_join(rbc_data, by = "ranid")  


```

```{r}
## getting some percentiles for arachidonic acid and egfr ratio
quantile(rbc_data$RBC_C20_4n6, probs = c(0.1, 0.45, 0.55, 0.9))
quantile(all_data2$ratio2, probs = c(0.1, 0.45, 0.55, 0.9), na.rm = TRUE)
```

```{r}
## some more random EDA
all_data2 %>% 
  group_by(H010) %>% 
  summarise(mean_egfr = mean(ratio2, na.rm = TRUE), median_egfr = median(ratio2, na.rm = TRUE), iqr_egfr = IQR(ratio2, na.rm = TRUE), mean_days = mean(days, na.rm = TRUE), median_days = median(days, na.rm = TRUE), iqr_days = IQR(days, na.rm = TRUE))

all_data2 %>% 
  summarise(median = median(days, na.rm = TRUE), IQR = IQR(days, na.rm = TRUE))
```

```{r}
## summing the relevant RBCs and stuff
all_data2 <- all_data2 %>% 
  rename(arachidonic = RBC_C20_4n6, eicosapentaenoic = RBC_C20_5n3, docosahexaenoic = RBC_C22_6n3, linoleic = RBC_C18_2n6, gamma_linoleic = RBC_C18_3n6, dihomo_gamma_linoleic = RBC_C20_3n6, eicosadiec = RBC_C20_2n6, docosapentaenoic1 = RBC_C22_5n6, docosapentaenoic2 = RBC_C22_5n3)


all_data2 <- all_data2 %>% 
  mutate(omega3 = (eicosapentaenoic + docosahexaenoic), omega6_1 = (arachidonic + linoleic + gamma_linoleic + dihomo_gamma_linoleic + eicosadiec + docosapentaenoic1), omega6_2 = (arachidonic + linoleic + gamma_linoleic + dihomo_gamma_linoleic + eicosadiec + docosapentaenoic2), ratio_rbc_3 = ratio2/omega3, ratio_rbc_6_1 = ratio2/omega6_1, ratio_rbc_6_2 = ratio2/omega6_2)
## ardenic acid not in dataset??
```

```{r}
export(all_data2, "rbc_data2.csv")
```

